version: '3'
services:
  app:
    #image: golang:1.13
    container_name: todo_app
    build:
      context: .
      dockerfile: ./build/dev/Dockerfile
    ports: 
      - 8080:5000 
    restart: on-failure
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - mysql  

  mysql:
    image: mysql:5.7
    container_name: todo_db_mysql
    ports: 
      - 3306:3306
    env_file:
      - .env
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
volumes:
  database_mysql:
